name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
        # add this step
    - name: Set up GOPATH
      run: |
        echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2  
      with:
        path: src/github.com/azak-azkaran/mvb-to-bucket-converter
      
    - name: Make Coverage Reports
      run: make coverage
      working-directory: src/github.com/azak-azkaran/mvb-to-bucket-converter
      
    - name: SonarCloud Scan
      # You may pin to the exact commit or the version.
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      with:
        args:
          # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            
          -Dsonar.projectKey=azak-azkaran_mvb-to-bucket-converter
          -Dsonar.organization=azak-azkaran-github
          -Dsonar.projectName=MVB to Bucket Converter
          -Dsonar.projectVersion=1.0
          # Encoding of the source code. Default is default system encoding
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.go.coverage.reportPaths=cover.out
          -Dsonar.go.tests.reportPaths=report.json
          # Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
          # This property is optional if sonar.modules is set.
          -Dsonar.sources=.
          -Dsonar.exclusions=**/*_test.go,**/vendor/**,*.html,cover.*

          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*_test.go
          -Dsonar.test.exclusions=**/vendor/**,*.html,cover.*
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Install Coveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=cover.out -service="github"
      working-directory: src/github.com/azak-azkaran/mvb-to-bucket-converter
